#   ----------------------------------------------------------------------
#   Copyright (C) 2018 World Intellectual Property Organization (WIPO).
#   All Rights Reserved.
#
#   v1.0    Kumar Vipin     Initial Version
#   ----------------------------------------------------------------------
AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Create certificates in North Virginia region

Parameters:
  NamePrefix:
    Description: Prefix added to the name of resources created in this stack (must be the same as the one of the pipeline)
    Type: String
    Default: Aws
  
  Environment:
    Description: Environment type
    Type: String

  HostedZoneId:
    Description:  Hosted Zone Id
    Type: String

  AwsDomainName:
    Description: Cdn Resource DomainName
    Type: String
  
Conditions:
  ifNotCustomResourceDomain : !Not [ !Equals [!Ref AwsDomainName, !Select [ 0, !Split [ 'web1.wipo.int', !Ref AwsDomainName ] ]] ]

Resources:
  AwsCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref AwsDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - !If 
          - ifNotCustomResourceDomain
          - DomainName: !Ref AwsDomainName
            HostedZoneId: !Ref HostedZoneId
          - !Ref "AWS::NoValue"

#  AwsCertificateArnParam:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: !Sub /${NamePrefix}/CfnAwsCertificateArn
#      Type: String
#      Value: !Ref AwsCertificate
#      Description: The AwsCertificateArn


Outputs:
  AwsCertificateArn:
    Description: Aws Certificate ARN
    Value: !Ref AwsCertificate
    Export: 
      Name: !Sub ${NamePrefix}-cdn-web-certificate