AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Creates the hosted zones

Parameters:

  NamePrefix:
    Description: Prefix added to the name of resources created in this stack
    Type: String
    
  BusinessUnit:
    Description: The name of the business unit (present in the account name)
    Type: String    

  Environment:
    Description: Environment type (controls various parameters of the deployment, ip ranges, size of the EC2 instances, tags, etc.)
    Type: String
    AllowedValues: [dev, acc, prd]
    Default: dev

  VpcId:
    Description: VPC id
    Type: String

Mappings:
  DomainMap:
    dev:
      Name: Aws.dev.wipo.int
    acc:
      Name: Aws.acc.wipo.int
    prd:
      Name: Aws.wipo.int

Resources:

  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: !Sub Public hosted zone for ${NamePrefix}
      Name: !Sub ${NamePrefix}.${BusinessUnit}.${Environment}.web1.wipo.int

  PublicSubDomainRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub NS definition for ${NamePrefix} sub-domain
      HostedZoneName: !Sub ${BusinessUnit}.${Environment}.web1.wipo.int.
      Name: !Sub ${NamePrefix}.${BusinessUnit}.${Environment}.web1.wipo.int.
      Type: NS
      TTL: 900
      ResourceRecords: !GetAtt PublicHostedZone.NameServers


  PrivateDnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties: 
      Description: !Sub Private dns namespace for ${NamePrefix}
      Name: !Sub ${NamePrefix}.${BusinessUnit}.${Environment}.intra1.wipo.int
      Vpc: !Ref VpcId

  #SSM PARAMETERS

  PublicHostedZoneParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/publicHostedZoneId
      Type: String
      Value: !Ref PublicHostedZone
      Description: The name of the public hosted zone

  PrivateDnsNamespaceParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/privateDnsNamespaceId
      Type: String
      Value: !Ref PrivateDnsNamespace
      Description: The private dns namespace

  PrivateDnsNamespaceArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/privateDnsNamespaceArn
      Type: String
      Value: !GetAtt PrivateDnsNamespace.Arn
      Description: The private dns namespace ARN

  PrivateDnsNamespaceName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/privateDnsNamespaceName
      Type: String
      Value: !Sub ${NamePrefix}.${BusinessUnit}.${Environment}.intra1.wipo.int
      Description: The private dns namespace name


  PublicHostedZoneSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/publicHostedDnsName
      Type: String
      Value: !Sub ${NamePrefix}.${BusinessUnit}.${Environment}.web1.wipo.int
      Description: The public dns namespace name

Outputs:

  PublicHostedZoneId:
    Description: The name of the public hosted zone
    Value: !Ref PublicHostedZone

  PublicHostedZoneName:
    Description: The name of the public hosted zone
    Value: !Sub ${NamePrefix}.${BusinessUnit}.${Environment}.web1.wipo.int