#   ----------------------------------------------------------------------
#   Copyright (C) 2018 World Intellectual Property Organization (WIPO).
#   All Rights Reserved.
#
#   v4.1  D. Onwunumah
#   ----------------------------------------------------------------------
AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Deploys the Aws infra system

Parameters:

  BuildId:
    Type: String
    Description: The identifier of the build

  Service:
    Description: The service name
    Type: String
    Default: Aws

  Environment:
    Description: Environment type (controls various parameters of the deployment, ip ranges, size of the EC2 instances, tags, etc.)
    Type: String
    AllowedValues: [dev, acc, prd]
    Default: dev

  NamePrefix:
    Description: Prefix added to the name of resources created in this stack (must be the same as the one of the pipeline)
    Type: String
    Default: Aws

  BusinessUnit:
    Description: The name of the business unit (present in the account name)
    Type: String
    Default: madrid

  ArtifactsAccount:
    Type: String
    Description: The ID of the account where the artifacts are stored (s3, ecr)
    Default: 1234567890 #todo

  ArtifactsBucket:
    Type: String
    Description: The name of the bucket where the artifacts are stored
    Default: Aws-artifacts-eu-central-1-1234567890

Conditions:

  IsDev: !Equals [!Ref Environment, dev]
  IsPrd: !Equals [!Ref Environment, prd]

Mappings:

  EnvironmentMap:
    dev:
      DBAccessCidrBlock: '10.0.0.0/8'  # All WIPO private space, for developers
      IngressCidrBlocks: 
          - 193.5.93.0/24
          - 3.126.58.0/24
      AwsAlias: 'cdn.Aws.madrid.dev.web1.wipo.int' # CDN_ALIAS.NAME_PREFIX.BU.ENV.wipo.int
      AwsAlternateAlias: ''
      LogRetentionDaysNum: 1
    acc:
      DBAccessCidrBlock: '10.0.0.0/8'  # All WIPO private space (for testing before commissioning prod)
      IngressCidrBlocks: 
          - 193.5.93.0/24
          - 3.126.58.0/24
      AwsAlias: 'cdn.Aws.madrid.acc.web1.wipo.int' # CDN_ALIAS.NAME_PREFIX.BU.ENV.wipo.int
      AwsAlternateAlias: ''
      LogRetentionDaysNum: 1
    prd:
      DBAccessCidrBlock: '10.132.100.196/32'  # Conor pc1
      IngressCidrBlocks: 
          - 193.5.93.0/24
          - 3.126.58.0/24
      AwsAlias: 'cdn.Aws.madrid.prd.web1.wipo.int' # CDN_ALIAS.NAME_PREFIX.BU.ENV.wipo.int
      AwsAlternateAlias: ''
      LogRetentionDaysNum: 7

      
Resources:

  Init:
    Type: AWS::CloudFormation::Stack
    Properties:
#      TemplateURL: !Sub https://${Service}-artifacts-${AWS::Region}-${ArtifactsAccount}.s3.amazonaws.com/builds/${BuildId}/templates/iac/init.yml
      TemplateURL: !Sub https://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}.amazonaws.com/builds/${BuildId}/templates/iac/template/init.yml
      Parameters:
        NamePrefix: !Ref NamePrefix
        LogRetentionDays: !FindInMap [EnvironmentMap, !Ref Environment, LogRetentionDaysNum]
      Tags:
        - Key: environment
          Value: !Ref Environment

  Infrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      #TemplateURL: !Sub https://${Service}-artifacts-${AWS::Region}-${ArtifactsAccount}.s3.amazonaws.com/builds/${BuildId}/templates/iac/infra.yml
      # https://Aws-artifacts-eu-central-1-551493771163.s3.eu-central-1.amazonaws.com/builds/24-04-24.0.TCVAdI4o/templates/iac/template/infra.yml
      TemplateURL: !Sub https://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}.amazonaws.com/builds/${BuildId}/templates/iac/template/infra.yml
      Parameters:
        NamePrefix: !Ref NamePrefix
        VpcCidrBlock: !Sub /${NamePrefix}/vpc/cidr
        CreateTransitGatewayAttachment: 'true'
      Tags:
        - Key: environment
          Value: !Ref Environment

  Dns:
    Type: AWS::CloudFormation::Stack
    Properties:
      #TemplateURL: !Sub https://${Service}-artifacts-${AWS::Region}-${ArtifactsAccount}.s3.amazonaws.com/builds/${BuildId}/templates/iac/dns.yml
      # https://Aws-artifacts-eu-central-1-551493771163.s3.eu-central-1.amazonaws.com/builds/24-04-24.0.TCVAdI4o/templates/iac/template/dns.yml
      TemplateURL: !Sub https://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}.amazonaws.com/builds/${BuildId}/templates/iac/template/dns.yml
      Parameters:
        NamePrefix: !Ref NamePrefix
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        VpcId: !GetAtt Infrastructure.Outputs.VpcId
      Tags:
        - Key: environment
          Value: !Ref Environment

#  CertificatesNorthVirginiaStackSet:
#    Type: AWS::CloudFormation::StackSet
#    DependsOn: [ Init, Dns ]
#    Properties:
#      # TemplateURL: !Sub https://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}.s3.amazonaws.com/templates/iac/template/certificates-us-east-1.yml
#      # s3://Aws-artifacts-eu-central-1-551493771163/builds/24-04-24.0.DUg6IG3G/templates/iac/template/certificates-us-east-1.yml
#      # s3://Aws-artifacts-eu-central-1-551493771163/builds/24-04-24.0.TCVAdI4o/templates/iac/template/certificates-us-east-1.yml
#      # s3://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}/builds/${BuildId}/templates/iac/template/certificates-us-east-1.yml
#      TemplateURL: !Sub https://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}.amazonaws.com/builds/${BuildId}/templates/iac/template/certificates-us-east-1.yml
#      Description: Create certificates in the us-east-1 region
#      AdministrationRoleARN: !GetAtt Init.Outputs.CloudformationAdminRoleArn
#      ExecutionRoleName: !GetAtt Init.Outputs.CloudformationExecutionRoleName
#      PermissionModel: SELF_MANAGED
#      Capabilities:
#        - CAPABILITY_IAM
#        - CAPABILITY_NAMED_IAM
#      StackInstancesGroup:
#        - DeploymentTargets:
#            Accounts:
#              - !Ref AWS::AccountId
#          Regions:
#            - us-east-1
#      StackSetName: !Sub "${NamePrefix}-certificates-us-east-1"
#      Parameters:
#       - ParameterKey: NamePrefix
#         ParameterValue: !Ref NamePrefix
#       - ParameterKey: Environment
#         ParameterValue: !Ref Environment
#       - ParameterKey: HostedZoneId
#         ParameterValue: !GetAtt Dns.Outputs.PublicHostedZoneId
#       - ParameterKey: AwsDomainName
#         ParameterValue: !If [IsPrd, !FindInMap [EnvironmentMap, !Ref Environment,AwsAlternateAlias] , !FindInMap [EnvironmentMap, !Ref Environment,AwsAlias] ]
#

#  WAFStack:
#    Type: AWS::CloudFormation::Stack
##    DependsOn: [ ApiLambda ]
#    Properties:
##      TemplateURL: !Sub https://${Service}-artifacts-${AWS::Region}-${ArtifactsAccount}.s3.amazonaws.com/builds/${BuildId}/templates/iac/waf.yml
#      TemplateURL: !Sub https://${NamePrefix}-artifacts-${AWS::Region}-${ArtifactsAccount}.s3.amazonaws.com/templates/iac/template/waf.yml
#      Parameters:
#        NamePrefix: !Ref NamePrefix
#        Environment: !Ref Environment
#        IngressCidr: !FindInMap [ EnvironmentMap, !Ref Environment, IngressCidrBlocks ]
#        ApiGateWayId: !GetAtt ApiLambda.Outputs.ApiId
#        ApiGateWayStage: !GetAtt ApiLambda.Outputs.ApiGatewayStage
