AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Creates the roles for cross account access

Parameters:

  NamePrefix:
    Description: Prefix added to the name of resources created in this stack
    Type: String
    Default: Aws
    
  VpcCidr:
    Description: The CIDR Block of the VPC
    Type: String
    Default: '10.41.217.0/24'
    AllowedPattern: '^((\d{1,3})\.){3}\d{1,3}/\d{1,2}$'

  Environment:
    Description: Environment type (controls various parameters of the deployment, ip ranges, size of the EC2 instances, tags, etc.)
    Type: String
    AllowedValues: [dev, acc, prd]
    Default: dev

Resources:

  VpcCidrBlock:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/vpc/cidr
      Type: String
      Value: !Ref VpcCidr
      Description: The CIDR Block of the VPC
      Tags:
        Environment: !Ref Environment
        Service: !Ref NamePrefix


                                       