#   ----------------------------------------------------------------------
#   Copyright (C) 2018 World Intellectual Property Organization (WIPO).
#   All Rights Reserved.
#
#   v1.0    Kumar Vipin     Initial Version
#   ----------------------------------------------------------------------
AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Template to configure WAF to allow access only to WIPO IPs

Parameters:
  NamePrefix:
    Description: Prefix added to the name of resources created in this stack (must be the same as the one of the pipeline)
    Type: String
  
  Environment:
    Description: Environment type (controls various parameters of the deployment, ip ranges, size of the EC2 instances, tags, etc.)
    Type: String
  
  IngressCidr:
    Description: The CIDR Block of the users allowed to access the app
    Type: List<String>

#  ApiGateWayId:
#    Type: String
#
#  ApiGateWayStage:
#    Type: String
    
Conditions:
  IsPrd: !Equals [!Ref Environment, prd]

Resources:
  WipoIpSetWhitelist:
    Type: AWS::WAF::IPSet
    # Condition: IsNotPrd
    Properties:
      Name: WIPO IPSet whitelisted
      IPSetDescriptors:
        - Type: IPV4
          Value: !Select [ 0, !Ref IngressCidr]

  WipoIpSetRule:
    Type: AWS::WAF::Rule
    # Condition: IsNotPrd
    Properties:
      Name: WipoIpSetRule
      MetricName: WipoIpSetRule
      Predicates:
        - DataId: !Ref WipoIpSetWhitelist
          Negated: false
          Type: IPMatch

  WebACLWipoIp:
    Type: AWS::WAF::WebACL
    # Condition: IsNotPrd
    Properties:
      Name: WipoIpSetACL
      DefaultAction:
        Type: BLOCK
      MetricName: WipoIpSetACL
      Rules:
        - Action:
            Type: ALLOW
          Priority: 1
          RuleId: !Ref WipoIpSetRule

  WipoIpSetWhitelistRegional:
    Type: AWS::WAFRegional::IPSet
    # Condition: IsNotPrd
    Properties:
      Name: WIPO IPSet whitelisted
      IPSetDescriptors:
        - Type: IPV4
          Value: !Select [ 0, !Ref IngressCidr]

  WipoIpSetRuleRegional:
    Type: AWS::WAFRegional::Rule
    # Condition: IsNotPrd
    Properties:
      Name: WipoIpSetRuleRegional
      MetricName: WipoIpSetRuleRegional
      Predicates:
        - DataId: !Ref WipoIpSetWhitelistRegional
          Negated: false
          Type: IPMatch

  WebACLWipoIpRegional:
    Type: AWS::WAFRegional::WebACL
    # Condition: IsNotPrd
    Properties:
      Name: WipoIpSetACLRegional
      DefaultAction:
        Type: BLOCK
      MetricName: WipoIpSetACLRegional
      Rules:
        - Action:
            Type: ALLOW
          Priority: 1
          RuleId: !Ref WipoIpSetRuleRegional

#  ApiGatewayWAFAssociation:
#    Type: AWS::WAFRegional::WebACLAssociation
#    Properties:
#      ResourceArn: !Sub 'arn:aws:apigateway:${AWS::Region}::/restapis/${ApiGateWayId}/stages/${ApiGateWayStage}'
#      WebACLId: !Ref WebACLWipoIpRegional

  #SSM PARAMETERS

  WebACLWipoIpRefParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/webACLWipoIpRef
      Type: String
      Value: !Ref WebACLWipoIp
      Description: The id of the WIPO Web ACL

  WebACLWipoIpRefRegionalParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${NamePrefix}/webACLWipoIpRefRegional
      Type: String
      Value: !Ref WebACLWipoIpRegional
      Description: The id of the WIPO Regional

Outputs:
  WebACLWipoIpRef:
    Value: !Ref WebACLWipoIp

  WebACLWipoIpRefRegional:
    Value: !Ref WebACLWipoIpRegional

  