AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Creates the roles for cross account access

Parameters:

  NamePrefix:
    Description: Prefix added to the name of resources created in this stack
    Type: String

  CicdAccount:
    Description: The id of the cicd account
    Type: String
    Default: '173148697964'

Conditions:

  isDevelopment: !Equals [ '452010797180' , !Ref AWS::AccountId]

Resources:

  CicdRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${NamePrefix}-cicd-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${CicdAccount}:root
                - !If [ isDevelopment, !Sub 'arn:aws:iam::${AWS::AccountId}:root', !Ref AWS::NoValue ]
            Action:
              - sts:AssumeRole
      Path: /

  CicdPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${NamePrefix}-cicd-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - cloudformation:*
              - s3:*
              - iam:PassRole
            Resource: '*'
      Roles: 
        - !Ref CicdRole

  KmsCicdPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${NamePrefix}-kms-cicd-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: 
              - !Sub arn:aws:kms:${AWS::Region}:${CicdAccount}:key/*
              - !Sub arn:aws:kms:us-east-1:${CicdAccount}:key/*
              - !If [ isDevelopment, !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*', !Ref AWS::NoValue ]
              - !If [ isDevelopment, !Sub 'arn:aws:kms:us-east-1:${AWS::AccountId}:key/*', !Ref AWS::NoValue ]
      Roles: 
        - !Ref CicdRole
        - !Ref DeploymentRole

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${NamePrefix}-deployment-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  DeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${NamePrefix}-deployment-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iam:*
            Resource: 
              - !Sub arn:aws:iam::${AWS::AccountId}:role/${NamePrefix}*
              - !Sub arn:aws:iam::${AWS::AccountId}:policy/${NamePrefix}*
              - !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/${NamePrefix}*
              - !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/*
          - Effect: Allow
            Action:
              - apigateway:*
              - acm:*
              - backup:*
              - backup-storage:*
              - cloudformation:*
              - cloudfront:*
              - cloudwatch:*
              - cognito-identity:*
              - cognito-idp:*
              - daynamodb:*
              - dynamodb:*
              - events:*
              - ec2:*
              - kms:*
              - lambda:*
              - logs:*
              - route53:*
              - s3:*
              - secretsmanager:*
              - sns:*
              - sqs:*
              - ssm:*
              - waf:*
              - wafv2:*
              - states:*              
            Resource: '*'
      Roles: 
        - !Ref DeploymentRole

Outputs:

  CicdRoleName:
    Description: The name of the cross account role
    Value: !Ref CicdRole
  
  CicdRoleArn:
    Description: The Arn of the cross account role
    Value: !GetAtt CicdRole.Arn

  DeploymentRoleName:
    Description: The Name of the deployment role
    Value: !Ref DeploymentRole

  DeploymentRoleArn:
    Description: The Arn of the deployment role
    Value: !GetAtt DeploymentRole.Arn
