AWSTemplateFormatVersion: 2010-09-09

Description: > 
  Creates the CASE Service deployment pipeline artifact on us-east-1

Parameters:

  NamePrefix:
    Description: Prefix added to the name of resources created in this stack. It correspond to the service tag
    Type: String

  Environment:
    Description: "Environment type (controls various parameters of the deployment, ip ranges, size of the EC2 instances, tags, etc.)"
    Type: String
    AllowedValues: [dev, acc, prd]

  DevelopmentAccount:
    Description: The id of the development account
    Type: String
    AllowedPattern: '^\d{12}$'
    Default: '452010797180'
    
  AcceptanceAccount:
    Description: The id of the acceptance account
    Type: String
    AllowedPattern: '^\d{12}$'
    Default: '329803703153'

  ProductionAccount:
    Description: The id of the production account
    Type: String
    AllowedPattern: '^\d{12}$'
    Default: '329803703153'
  
  BudgetUnitCode:
    Description: The value for the budget-unit-code tag
    Type: String
    Default: '0048'
  
  BusinessImpactLevel: 
    Description: The value for the business-impact-level tag
    Type: String
    AllowedValues: ['1', '2', '3', '4']
    Default: '2'
                
  BusinessOwner: 
    Description: The value for the business-owner tag
    Type: String
    Default: 'william.meredith@wipo.int'
  
  BusinessUnitName: 
    Description: The value for the business-unit-name tag
    Type: String
    Default: 'IP Office Business Solutions'

  DataClassification: 
    Description: The value for the data-classification tag
    Type: String
    AllowedValues: ['public', 'for_official_use_only', 'confidential', 'highly_confidential']
    Default: 'confidential'

  TechnicalOwner: 
    Description: The value for the technical-owner tag
    Type: String
    Default: 'daniel.cheng@wipo.int'

  Service:
    Description: Value of the service tag
    Type: String
    Default: 'case'
    
  Section:
    Description: Value of the section tag
    Type: String
    Default: 'ipobs'

Mappings:
  
  Constant:
    Account:
      Cicd: '173148697964'

Resources:

  KMSKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Used by Assumed Roles in dev/acc/prd accounts to Encrypt/Decrypt artifacts
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref AWS::StackName
        Statement:
          - Sid: Allows admin of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
              - kms:UntagResource
              - kms:TagResource
            Resource: "*"
          - Sid: Allow use of the key by IAM
            Effect: Allow
            Principal:
              AWS: 
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
              - kms:UntagResource
              - kms:TagResource
            Resource: "*"
          - Sid: Allow use of the key by other accounts
            Effect: Allow
            Principal:
              AWS: 
                - !Sub arn:aws:iam::${DevelopmentAccount}:root
                - !Sub arn:aws:iam::${AcceptanceAccount}:root
                - !Sub arn:aws:iam::${ProductionAccount}:root
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: "*"

  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${NamePrefix}-crossaccount-cmk
      TargetKeyId: !Ref KMSKey

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${NamePrefix}-artifacts-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KMSKey.Arn
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced        
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Id: !Sub ${NamePrefix}-artifacts-bucket-policy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub arn:aws:iam::${DevelopmentAccount}:root
                - !Sub arn:aws:iam::${AcceptanceAccount}:root
                - !Sub arn:aws:iam::${ProductionAccount}:root
            Action: 
              - s3:ListBucket
              - s3:GetObject
            Resource: 
              - !Sub arn:aws:s3:::${ArtifactsBucket}
              - !Sub arn:aws:s3:::${ArtifactsBucket}/*

Outputs:

  ArtifactsBucket:
    Description: "The name of the artifact bucket"
    Value: !Ref ArtifactsBucket

  ArtifactsBucketArn:
    Description: "The Arn of the artifact bucket"
    Value: !GetAtt ArtifactsBucket.Arn

  KMSKeyArn:
    Description: "The Arn of the KMS key"
    Value: !GetAtt KMSKey.Arn
