version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./s3-data:/s3-data
    command: server --console-address ":9001" /data
    env_file: .s3Env
    restart: always